---
title: "Assignment2"
output:
  word_document: default
  html_document:
    df_print: paged
  pdf_document: default
date: "2024-04-02"
---

```{r}
#Install required packages
#https://cran.r-project.org/web/packages/shiny/index.html
install.packages("shiny", dependencies = TRUE)
#https://cran.r-project.org/web/packages/shinythemes/index.html
install.packages("shinythemes", dependencies = TRUE)
#https://cran.r-project.org/web/packages/arules/index.html
install.packages("arules", dependencies = TRUE)
#https://cran.r-project.org/web/packages/arulesViz/index.html
install.packages("arulesViz", dependencies = TRUE)
#https://cran.r-project.org/web/packages/gtools/index.html
install.packages("gtools", dependencies = TRUE)
#https://cran.r-project.org/web/packages/gtools/index.html
install.packages("klaR", dependencies = TRUE)
library(XML)
datasetResults <- xmlParse("electronicsdb.xml")
datasetResults
```

```{r}
# Load required libraries
library(arules)
library(dplyr)
```
```{r}
# Create a data frame from the transactions
transactions <- data.frame(
  TransID = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10),
  Items = c("Bread, Milk", "Bread, Cookies, Juice, Eggs", "Milk, Cookies, Juice, Soda",
            "Bread, Milk, Juice, Eggs", "Bread, Milk, Eggs, Soda", "Bread, Milk, Juice, Coffee",
            "Bread, Milk, Eggs", "Coffee, Cookies", "Bread, Coffee, Eggs", "Milk, Eggs")
)

```

```{r}
# Convert the data frame to a transactions object
trans <- as(split(transactions$Items, transactions$TransID), "transactions")

```

```{r}
# Apply the Apriori algorithm with minimum support of 0.2
rules <- apriori(trans, parameter = list(support = 0.2, maxlen = 10))

```
```{r}
# Print the frequent itemsets
print(inspect(sort(rules, by = "support")))

```
```{r}
# Generate rules with minimum confidence of 0.5 for 3-item frequent itemsets
rules_3items <- apriori(trans, parameter = list(support = 0.2, confidence = 0.5, maxlen = 3))

```
```{r}
# Print the rules for 3-item frequent itemsets
print(inspect(rules_3items))
```

